import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('create_menu_drink_tables').insert([

      { menu_id: 1, drink_id: 1 },
      { menu_id: 1, drink_id: 2 },
      { menu_id: 1, drink_id: 3 },
      { menu_id: 1, drink_id: 4 },
      { menu_id: 1, drink_id: 5 },
      { menu_id: 1, drink_id: 6 },
      { menu_id: 1, drink_id: 7 },
      { menu_id: 1, drink_id: 8 },
      { menu_id: 1, drink_id: 9 },
      { menu_id: 1, drink_id: 10 },
      { menu_id: 1, drink_id: 11 },

      { menu_id: 2, drink_id: 1 },
      { menu_id: 2, drink_id: 2 },
      { menu_id: 2, drink_id: 3 },
      { menu_id: 2, drink_id: 4 },
      { menu_id: 2, drink_id: 5 },
      { menu_id: 2, drink_id: 6 },
      { menu_id: 2, drink_id: 7 },
      { menu_id: 2, drink_id: 8 },
      { menu_id: 2, drink_id: 9 },
      { menu_id: 2, drink_id: 10 },
      { menu_id: 2, drink_id: 11 },

      { menu_id: 3, drink_id: 1 },
      { menu_id: 3, drink_id: 2 },
      { menu_id: 3, drink_id: 3 },
      { menu_id: 3, drink_id: 4 },
      { menu_id: 3, drink_id: 5 },
      { menu_id: 3, drink_id: 6 },
      { menu_id: 3, drink_id: 7 },
      { menu_id: 3, drink_id: 8 },
      { menu_id: 3, drink_id: 9 },
      { menu_id: 3, drink_id: 10 },
      { menu_id: 3, drink_id: 11 },

      { menu_id: 4, drink_id: 1 },
      { menu_id: 4, drink_id: 2 },
      { menu_id: 4, drink_id: 3 },
      { menu_id: 4, drink_id: 4 },
      { menu_id: 4, drink_id: 5 },
      { menu_id: 4, drink_id: 6 },
      { menu_id: 4, drink_id: 7 },
      { menu_id: 4, drink_id: 8 },
      { menu_id: 4, drink_id: 9 },
      { menu_id: 4, drink_id: 10 },
      { menu_id: 4, drink_id: 11 },

      { menu_id: 5, drink_id: 1 },
      { menu_id: 5, drink_id: 2 },
      { menu_id: 5, drink_id: 3 },
      { menu_id: 5, drink_id: 4 },
      { menu_id: 5, drink_id: 5 },
      { menu_id: 5, drink_id: 6 },
      { menu_id: 5, drink_id: 7 },
      { menu_id: 5, drink_id: 8 },
      { menu_id: 5, drink_id: 9 },
      { menu_id: 5, drink_id: 10 },
      { menu_id: 5, drink_id: 11 },

      { menu_id: 6, drink_id: 1 },
      { menu_id: 6, drink_id: 2 },
      { menu_id: 6, drink_id: 3 },
      { menu_id: 6, drink_id: 4 },
      { menu_id: 6, drink_id: 5 },
      { menu_id: 6, drink_id: 6 },
      { menu_id: 6, drink_id: 7 },
      { menu_id: 6, drink_id: 8 },
      { menu_id: 6, drink_id: 9 },
      { menu_id: 6, drink_id: 10 },
      { menu_id: 6, drink_id: 11 },

      { menu_id: 7, drink_id: 1 },
      { menu_id: 7, drink_id: 2 },
      { menu_id: 7, drink_id: 3 },
      { menu_id: 7, drink_id: 4 },
      { menu_id: 7, drink_id: 5 },
      { menu_id: 7, drink_id: 6 },
      { menu_id: 7, drink_id: 7 },
      { menu_id: 7, drink_id: 8 },
      { menu_id: 7, drink_id: 9 },
      { menu_id: 7, drink_id: 10 },
      { menu_id: 7, drink_id: 11 },

      { menu_id: 8, drink_id: 1 },
      { menu_id: 8, drink_id: 2 },
      { menu_id: 8, drink_id: 3 },
      { menu_id: 8, drink_id: 4 },
      { menu_id: 8, drink_id: 5 },
      { menu_id: 8, drink_id: 6 },
      { menu_id: 8, drink_id: 7 },
      { menu_id: 8, drink_id: 8 },
      { menu_id: 8, drink_id: 9 },
      { menu_id: 8, drink_id: 10 },
      { menu_id: 8, drink_id: 11 },

      { menu_id: 9, drink_id: 1 },
      { menu_id: 9, drink_id: 2 },
      { menu_id: 9, drink_id: 3 },
      { menu_id: 9, drink_id: 4 },
      { menu_id: 9, drink_id: 5 },
      { menu_id: 9, drink_id: 6 },
      { menu_id: 9, drink_id: 7 },
      { menu_id: 9, drink_id: 8 },
      { menu_id: 9, drink_id: 9 },
      { menu_id: 9, drink_id: 10 },
      { menu_id: 9, drink_id: 11 },

      { menu_id: 10, drink_id: 1 },
      { menu_id: 10, drink_id: 2 },
      { menu_id: 10, drink_id: 3 },
      { menu_id: 10, drink_id: 4 },
      { menu_id: 10, drink_id: 5 },
      { menu_id: 10, drink_id: 6 },
      { menu_id: 10, drink_id: 7 },
      { menu_id: 10, drink_id: 8 },
      { menu_id: 10, drink_id: 9 },
      { menu_id: 10, drink_id: 10 },
      { menu_id: 10, drink_id: 11 },

      { menu_id: 11, drink_id: 1 },
      { menu_id: 11, drink_id: 2 },
      { menu_id: 11, drink_id: 3 },
      { menu_id: 11, drink_id: 4 },
      { menu_id: 11, drink_id: 5 },
      { menu_id: 11, drink_id: 6 },
      { menu_id: 11, drink_id: 7 },
      { menu_id: 11, drink_id: 8 },
      { menu_id: 11, drink_id: 9 },
      { menu_id: 11, drink_id: 10 },
      { menu_id: 11, drink_id: 11 },
    ])
  }
}
